version: "3.9"

services:
    server_cesicar:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/home/app
        networks:
            - api_cesicar_default  # Conecta el servicio a la red existente

networks:
    api_cesicar_default:
        external:
            name: api_cesicar_default  # Nombre de la red existente
