version: "3.9"

services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        container_name: server_cesicar
        ports:
            - 5000:5000
        links:
            - db
        volumes:
            - .:/home/app


    db:
        image: mysql
        container_name: db_cesicar
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api_cesicar
            MYSQL_USER: api_cesicar
            MYSQL_PASSWORD: api_cesicar


    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmni_cesicar
        depends_on:
            - db
        ports:
            - 8080:8080
        environment:
            PMA_HOST: db
volumes:
    db-data:

