version: "3.9"

services:
    appmobile_backend_cesicar:
        container_name: appmobile_backend_cesicar-container
        image: barbaralzb/appmobile_backend_cesicar-image:latest
        build: .
        dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/home/app
        networks:
            - api_cesicar_default  # Conecta el servicio a la red existente

networks:
    api_cesicar_default:
        external:
            name: api_cesicar_default  # Nombre de la red existente
