version: "3.9"

services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        container_name: server_cesicar
        ports:
            - 5000:5000
        volumes:
            - .:/home/app
        networks:
            - api_cesicar_default  # Conecta el servicio a la red existente

    db:
        image: mysql
        container_name: db_cesicar
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api_cesicar
            MYSQL_USER: api_cesicar
            MYSQL_PASSWORD: api_cesicar
        networks:
            - api_cesicar_default  # Conecta el servicio a la red existente

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_cesicar
        depends_on:
            - db
        ports:
            - 8080:8080
        environment:
            PMA_HOST: db
        networks:
            - api_cesicar_default  # Conecta el servicio a la red existente

networks:
    api_cesicar_default:
        external: true  # Indica que esta red ya existe y es externa a este archivo

volumes:
    db-data: