name: Merge to Main if Tests Pass

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "barbaralizama.proj@gmail.com" && git config --global user.name "Barbara"

    - name: Run Tests
      run: npm test

    - name: Merge to Main if Tests Pass
      run: |
        if [ ${{ success() }} = true ]; then
          git checkout main
          git merge --no-ff develop -m "Merge develop into main"
          git push origin main
        else
          echo "Tests failed, not merging to main."
        fi
